version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t app -f .circleci/Dockerfile .
      - run:
          name: Publish Docker Image
          command: |
            set -e
            docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
            case "$CIRCLE_BRANCH" in
              master) export moving_tag="prod"
                ;;
              stage) export moving_tag="beta"
                ;;
              *) export moving_tag="alpha"
                ;;
            esac
            docker tag app "jaredallard/triton-converter:${moving_tag}"
            docker push "jaredallard/triton-converter:${moving_tag}"

  tests:
    docker:
      - image: jaredallard/triton-base
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn
      - save_cache:
          key: yarn-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - run: yarn test

workflows:
  version: 2
  test-push:
    jobs:
      - tests:
          context: Docker
          filters:
            branches:
              only:
                - master
                - stage
                - develop 
      - build:
          context: Docker
          requires:
            - tests
          filters:
            branches:
              only:
                - master
                - stage
                - develop
