jobs:
  build:
    docker:
    - image: docker:19.03.5
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: DOCKER_BUILDKIT=1 docker build --progress=plain -t tritonmedia/converter
          -f Dockerfile .
        name: Build "tritonmedia/converter" Docker Image
    - run:
        command: echo "$DOCKER_PASSWORD" | docker login --username "${DOCKER_USERNAME}"
          --password-stdin && docker push tritonmedia/converter
        name: Publish "tritonmedia/converter" Docker Image
  tests:
    docker:
    - image: tritonmedia/base
    steps:
    - checkout
    - restore_cache:
        key: yarn-{{ checksum "package.json" }}
    - run:
        command: yarn --frozen-lockfile
        name: Fetch Dependencies
    - save_cache:
        key: yarn-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        command: yarn test
        name: Run Tests
version: 2
workflows:
  build-push:
    jobs:
    - tests:
        context: Docker
    - build:
        context: Docker
        requires:
        - tests
  version: 2
